import type { UiLang } from "./i18n";
const labels: Record<UiLang, readonly string[]> = {
  "en-US": ["Create image", "Describe your image", "Shape", "Square", "Landscape", "Portrait", "Use the AI answer as context", "Creating image…", "Save image", "AI-generated with Grok Imagine", "Close", "The image couldn’t be created. Try again.", "Image creation is temporarily limited. Try again later.", "Image creation isn’t set up yet.", "This image was filtered. Try a different description.", "Create one image from your description. Edit it before creating."],
  "bn-BD": ["ছবি তৈরি করুন", "আপনার ছবির বর্ণনা দিন", "আকৃতি", "বর্গাকার", "আড়াআড়ি", "লম্বালম্বি", "AI উত্তরটি প্রেক্ষাপট হিসেবে ব্যবহার করুন", "ছবি তৈরি হচ্ছে…", "ছবি সংরক্ষণ করুন", "Grok Imagine দিয়ে AI-তে তৈরি", "বন্ধ করুন", "ছবি তৈরি করা যায়নি। আবার চেষ্টা করুন।", "ছবি তৈরি সাময়িকভাবে সীমিত। পরে চেষ্টা করুন।", "ছবি তৈরি এখনও চালু হয়নি।", "এই ছবি ফিল্টার করা হয়েছে। অন্য বর্ণনা দিন।", "আপনার বর্ণনা থেকে একটি ছবি তৈরি করুন। তৈরির আগে সম্পাদনা করুন।"],
  "hi-IN": ["चित्र बनाएँ", "अपने चित्र का वर्णन करें", "आकार", "वर्गाकार", "क्षैतिज", "लंबवत", "AI उत्तर को संदर्भ के रूप में उपयोग करें", "चित्र बन रहा है…", "चित्र सहेजें", "Grok Imagine से AI द्वारा बनाया गया", "बंद करें", "चित्र नहीं बना। फिर प्रयास करें।", "चित्र निर्माण अभी सीमित है। बाद में प्रयास करें।", "चित्र निर्माण अभी उपलब्ध नहीं है।", "यह चित्र फ़िल्टर किया गया। दूसरा वर्णन दें।", "अपने वर्णन से एक चित्र बनाएँ। बनाने से पहले संपादित करें।"],
  "ar-SA": ["إنشاء صورة", "صِف صورتك", "الشكل", "مربع", "أفقي", "عمودي", "استخدام إجابة الذكاء الاصطناعي كسياق", "جارٍ إنشاء الصورة…", "حفظ الصورة", "صورة مولدة بالذكاء الاصطناعي باستخدام Grok Imagine", "إغلاق", "تعذر إنشاء الصورة. حاول مجددًا.", "إنشاء الصور محدود مؤقتًا. حاول لاحقًا.", "إنشاء الصور غير مُعد بعد.", "تمت تصفية الصورة. جرّب وصفًا مختلفًا.", "أنشئ صورة واحدة من وصفك. عدّل الوصف قبل الإنشاء."],
  "es-ES": ["Crear imagen", "Describe tu imagen", "Formato", "Cuadrado", "Horizontal", "Vertical", "Usar la respuesta de IA como contexto", "Creando imagen…", "Guardar imagen", "Generada con IA por Grok Imagine", "Cerrar", "No se pudo crear la imagen. Inténtalo de nuevo.", "La creación de imágenes está limitada temporalmente. Inténtalo más tarde.", "La creación de imágenes aún no está configurada.", "La imagen fue filtrada. Prueba otra descripción.", "Crea una imagen a partir de tu descripción. Edítala antes de crearla."],
  "fr-FR": ["Créer une image", "Décrivez votre image", "Format", "Carré", "Paysage", "Portrait", "Utiliser la réponse IA comme contexte", "Création de l’image…", "Enregistrer l’image", "Générée par IA avec Grok Imagine", "Fermer", "Impossible de créer l’image. Réessayez.", "La création d’images est temporairement limitée. Réessayez plus tard.", "La création d’images n’est pas encore configurée.", "Cette image a été filtrée. Essayez une autre description.", "Créez une image à partir de votre description. Modifiez-la avant la création."],
  "zh-CN": ["创建图片", "描述你的图片", "形状", "正方形", "横向", "纵向", "使用 AI 回答作为背景", "正在创建图片…", "保存图片", "由 Grok Imagine AI 生成", "关闭", "无法创建图片，请重试。", "图片创建暂时受限，请稍后重试。", "图片创建尚未配置。", "图片已被过滤，请尝试其他描述。", "根据你的描述创建一张图片。创建前可以修改描述。"],
  "ja-JP": ["画像を作成", "画像を説明してください", "形状", "正方形", "横長", "縦長", "AIの回答を参考にする", "画像を作成中…", "画像を保存", "Grok ImagineによるAI生成画像", "閉じる", "画像を作成できませんでした。もう一度お試しください。", "画像作成は一時的に制限されています。後でお試しください。", "画像作成はまだ設定されていません。", "画像がフィルタリングされました。別の説明をお試しください。", "説明から画像を1枚作成します。作成前に編集できます。"],
  "pt-BR": ["Criar imagem", "Descreva sua imagem", "Formato", "Quadrado", "Paisagem", "Retrato", "Usar a resposta de IA como contexto", "Criando imagem…", "Salvar imagem", "Gerada por IA com Grok Imagine", "Fechar", "Não foi possível criar a imagem. Tente novamente.", "A criação de imagens está temporariamente limitada. Tente mais tarde.", "A criação de imagens ainda não está configurada.", "Esta imagem foi filtrada. Tente outra descrição.", "Crie uma imagem com sua descrição. Edite antes de criar."],
  "de-DE": ["Bild erstellen", "Beschreibe dein Bild", "Format", "Quadrat", "Querformat", "Hochformat", "KI-Antwort als Kontext verwenden", "Bild wird erstellt…", "Bild speichern", "Mit Grok Imagine KI-generiert", "Schließen", "Das Bild konnte nicht erstellt werden. Versuche es erneut.", "Die Bilderstellung ist vorübergehend begrenzt. Versuche es später.", "Die Bilderstellung ist noch nicht eingerichtet.", "Dieses Bild wurde gefiltert. Versuche eine andere Beschreibung.", "Erstelle ein Bild aus deiner Beschreibung. Bearbeite sie vor dem Erstellen."],
};
export function imageCopy(lang: UiLang) {
  const [create, prompt, shape, square, landscape, portrait, context, creating, save, generated, close, error, limited, unconfigured, blocked, hint] = labels[lang];
  return { create, prompt, shape, square, landscape, portrait, context, creating, save, generated, close, error, limited, unconfigured, blocked, hint };
}
