import type { UiLang } from "./i18n.ts";

export type { UiLang } from "./i18n.ts";

/** Every visible string in Folio's interface. Each language must fill every field. */
export type UiCopy = {
  search: string;
  clearSearch: string;
  trending: string;
  recent: string;
  clear: string;
  h1: string;
  blurb: string;
  howTitle: string;
  how1: string;
  how2: string;
  how3before: string;
  howTo: string;
  how3mid: string;
  about: string;
  how3after: string;
  sourcesOff: string;
  web: string;
  wiki: string;
  grok: string;
  images: string;
  on: string;
  off: string;
  optional: string;
  nothing: string;
  searchFor: string;
  noResponse: string;
  nothingPage: string;
  noMatches: string;
  openNew: string;
  webNote: string;
  imagesNote: string;
  shareResults: string;
  previous: string;
  next: string;
  page: string;
  deepDive: string;
  aiAnswer: string;
  aiBadge: string;
  asking: string;
  writing: string;
  tryAgain: string;
  failedSo: string;
  writtenBy: string;
  checkSources: string;
  aiUnconfigured: string;
  aiNoContext: string;
  aiError: string;
  image: string;
  locations: string;
  locationsFailed: string;
  map: string;
  definitions: string;
  readArticle: string;
  aboutResults: string;
  resultOne: string;
  resultMany: string;
  footerSearch: string;
  footerAbout: string;
  footerPrivacy: string;
  footerHow: string;
  language: string;
  model: string;
  searchModels: string;
  homeTitle: string;
  searchedAs: string;
  webSearchedAs: string;
  queryTranslateFailed: string;
  listTranslateFailed: string;
  translatePartial: string;
  grokSearchedAs: string;
  shareText: string;
  aiModels: string;
  noModels: string;
  selected: string;
  sourceN: string;
  pages: string;
  noteNotSetUp: string;
  notePaidPlan: string;
  listen: string;
  listenAnswer: string;
  pause: string;
  resume: string;
  stop: string;
  closePlayer: string;
  close: string;
  previousResult: string;
  nextResult: string;
  openPage: string;
  fullImage: string;
  loadingPreview: string;
  errorTitle: string;
  errorRetry: string;
  errorHome: string;
  errorTranslateHint: string;
  readingPage: string;
  pageUnavailable: string;
  showContents: string;
  hideContents: string;
  translating: string;
  translateFailed: string;
  noVoice: string;
  controls: string;
  speed: string;
  voices: string;
  sharePage: string;
  contents: string;
  backToSearch: string;
  englishOnly: string;
};

const en: UiCopy = {
  search: "Search",
  clearSearch: "Clear search",
  trending: "Trending now",
  recent: "Recent",
  clear: "Clear",
  h1: "Search the web, Wikipedia, and Grokipedia",
  blurb:
    "Search the web with Folio by Zip1. Explore web results and optional Wikipedia and Grokipedia sources from one simple search interface.",
  howTitle: "How Folio works",
  how1:
    "Type a query in the search bar and press the search button. The model menu in that bar chooses which model writes the short AI answer. Every search includes that answer, with numbered links to the results it used. The answer can be wrong or leave things out, so the lists under it are there to check.",
  how2:
    "Web results are included. Wikipedia and Grokipedia start on, and you can turn either one off. Images starts off. Turning it on adds pictures from Bing’s public image results. If Web, Wikipedia, Grokipedia, and Images are all off, the search button stays disabled until one of them is on again. After a search, those switches sit with the search box. On this page they stay hidden until every source is off.",
  how3before: "Select a result to open a preview in this window. Open page leaves Folio and goes to that address in the same window.",
  howTo: "How to search",
  how3mid: "explains the model menu, pages, and previews.",
  about: "About Folio",
  how3after: "explains what this site is and what it is not.",
  sourcesOff: "Turn on Web, Wikipedia, Grokipedia, or Images to search.",
  web: "Web",
  wiki: "Wikipedia",
  grok: "Grokipedia",
  images: "Images",
  on: "On",
  off: "Off",
  optional: "optional",
  nothing: "Nothing matched. Try fewer words, or switch on another source.",
  searchFor: "Search for",
  noResponse: "{source} didn’t respond. The other sources still ran.",
  nothingPage: "Nothing on this page.",
  noMatches: "No matches in {source}.",
  openNew: "Open {title} in a new tab",
  webNote: "Web listings via Bing’s public results feed.",
  imagesNote: "Images via Bing’s public image results, with SafeSearch set to moderate.",
  shareResults: "Share these results",
  previous: "Previous",
  next: "Next",
  page: "{label} page {n}",
  deepDive: "Deep dive into {topic}",
  aiAnswer: "AI answer",
  aiBadge: "AI-generated · can be wrong",
  asking: "Asking {model} for a short answer from the top results…",
  writing: "Writing a short answer from the top results…",
  tryAgain: "Try again",
  failedSo: "{failed} didn’t answer, so {provider} did.",
  writtenBy: "Written by {provider} ({model}) from the results on this page. It can be wrong or leave things out, so check the sources.",
  checkSources: "check the sources",
  aiUnconfigured: "AI answers aren’t set up yet.",
  aiNoContext: "AI answers need results from at least one source to work from.",
  aiError: "The AI answer didn’t load. The other sources still ran.",
  image: "Image",
  locations: "Location references",
  locationsFailed: "Location references didn’t load.",
  map: "Map",
  definitions: "Definitions",
  readArticle: "Read the article",
  aboutResults: "About {n} results",
  resultOne: "{n} result",
  resultMany: "{n} results",
  footerSearch: "Search",
  footerAbout: "About",
  footerPrivacy: "Privacy",
  footerHow: "How to search",
  language: "Language",
  model: "Model",
  searchModels: "Search models",
  homeTitle: "Folio by Zip1 — Web, Wikipedia & Grokipedia Search",
  searchedAs: "Wikipedia was searched as",
  webSearchedAs: "The web was searched as",
  queryTranslateFailed: "Your words could not be translated, so they were searched as typed.",
  listTranslateFailed: "Grokipedia results could not be translated and are shown in English.",
  translatePartial: "Part of this text could not be translated and is shown in the original language.",
  grokSearchedAs: "Grokipedia (English only) was searched as",
  shareText: "Search results for “{q}” on Folio",
  aiModels: "AI models",
  noModels: "No models",
  selected: "Selected",
  sourceN: "Source {n}: {title}",
  pages: "{label} pages",
  noteNotSetUp: "not set up",
  notePaidPlan: "needs a paid plan",
  listen: "Listen",
  listenAnswer: "Listen to the answer",
  pause: "Pause",
  resume: "Resume",
  stop: "Stop reading",
  closePlayer: "Close player",
  close: "Close",
  previousResult: "Previous result",
  nextResult: "Next result",
  openPage: "Open page",
  fullImage: "View full-size image",
  loadingPreview: "Loading the full preview…",
  errorTitle: "Something went wrong",
  errorRetry: "Try again",
  errorHome: "Go to the home page",
  errorTranslateHint: "A browser translation tool may have changed this page while it was updating. Try again, or turn off page translation for this site and use the language menu instead.",
  readingPage: "Reading the page…",
  pageUnavailable: "This site could not be read here (it may block outside access). Showing the search snippet; open the page to read it all.",
  showContents: "Show contents",
  hideContents: "Hide contents",
  translating: "Translating…",
  translateFailed: "Translation didn’t load. The original text is still shown.",
  noVoice: "This browser has no voice installed for this language, so the reading may use another voice.",
  controls: "Reading controls",
  speed: "Reading speed",
  voices: "Voices",
  sharePage: "Share this page",
  contents: "Contents",
  backToSearch: "Back to search",
  englishOnly: "The full text of this page is in English.",
};

export const UI: Record<UiLang, UiCopy> = {
  "en-US": en,
  "bn-BD": {
    search: "খুঁজুন",
    clearSearch: "খোঁজ মুছুন",
    trending: "এখন আলোচিত",
    recent: "সাম্প্রতিক",
    clear: "মুছুন",
    h1: "ওয়েব, উইকিপিডিয়া ও Grokipedia খুঁজুন",
    blurb: "Zip1-এর Folio দিয়ে ওয়েব খুঁজুন। একটি সহজ খোঁজে ওয়েব ফল এবং ঐচ্ছিক উইকিপিডিয়া ও Grokipedia উৎস দেখুন।",
    howTitle: "Folio কীভাবে কাজ করে",
    how1: "খোঁজের ঘরে প্রশ্ন লিখে খোঁজ বোতাম চাপুন। সেই ঘরের মডেল মেনু ঠিক করে কোন মডেল ছোট AI উত্তর লিখবে। প্রতিটি খোঁজে সেই উত্তর থাকে, এবং যে ফল সে ব্যবহার করেছে তার নম্বর সংযোগ থাকে। উত্তর ভুল হতে পারে বা কিছু বাদ যেতে পারে, তাই নিচের তালিকা মিলিয়ে দেখার জন্য।",
    how2: "ওয়েব ফল থাকে। উইকিপিডিয়া ও Grokipedia শুরুতে চালু, দুটিই বন্ধ করা যায়। ছবি শুরুতে বন্ধ। চালু করলে Bing-এর প্রকাশ্য ছবি যোগ হয়। ওয়েব, উইকিপিডিয়া, Grokipedia ও ছবি সব বন্ধ থাকলে খোঁজ বোতাম নিষ্ক্রিয় থাকে, যতক্ষণ না একটি আবার চালু হয়। খোঁজের পর এই সুইচগুলো খোঁজের ঘরের সাথে থাকে। এই পাতায় সব উৎস বন্ধ না হওয়া পর্যন্ত সেগুলো লুকানো থাকে।",
    how3before: "একটি ফল বেছে নিলে এই উইন্ডোতে প্রিভিউ খোলে। পাতা খুলুন Folio ছেড়ে একই উইন্ডোতে সেই ঠিকানায় যায়।",
    howTo: "কীভাবে খুঁজবেন",
    how3mid: "মডেল মেনু, পাতা ও প্রিভিউ বোঝায়।",
    about: "Folio সম্পর্কে",
    how3after: "বোঝায় এই সাইট কী এবং কী নয়।",
    sourcesOff: "খোঁজার জন্য ওয়েব, উইকিপিডিয়া, Grokipedia বা ছবি চালু করুন।",
    web: "ওয়েব",
    wiki: "উইকিপিডিয়া",
    grok: "Grokipedia",
    images: "ছবি",
    on: "চালু",
    off: "বন্ধ",
    optional: "ঐচ্ছিক",
    nothing: "কিছু মেলেনি। কম শব্দ ব্যবহার করুন, বা অন্য উৎস চালু করুন।",
    searchFor: "খোঁজ",
    noResponse: "{source} সাড়া দেয়নি। অন্য উৎস চলেছে।",
    nothingPage: "এই পাতায় কিছু নেই।",
    noMatches: "{source}-এ কোনো মিল নেই।",
    openNew: "{title} নতুন ট্যাবে খুলুন",
    webNote: "ওয়েব তালিকা Bing-এর প্রকাশ্য ফল থেকে।",
    imagesNote: "ছবি Bing-এর প্রকাশ্য ছবির ফল থেকে, SafeSearch মাঝারি।",
    shareResults: "এই ফল শেয়ার করুন",
    previous: "আগের",
    next: "পরের",
    page: "{label} পাতা {n}",
    deepDive: "{topic} নিয়ে গভীর খোঁজ",
    aiAnswer: "AI উত্তর",
    aiBadge: "AI-এর লেখা · ভুল হতে পারে",
    asking: "শীর্ষ ফল থেকে ছোট উত্তরের জন্য {model}-কে বলা হচ্ছে…",
    writing: "শীর্ষ ফল থেকে ছোট উত্তর লেখা হচ্ছে…",
    tryAgain: "আবার চেষ্টা",
    failedSo: "{failed} উত্তর দেয়নি, তাই {provider} দিয়েছে।",
    writtenBy: "{provider} ({model}) এই পাতার ফল থেকে লিখেছে। এটি ভুল হতে পারে বা কিছু বাদ যেতে পারে, তাই উৎস মিলিয়ে দেখুন।",
    checkSources: "উৎস মিলিয়ে দেখুন",
    aiUnconfigured: "AI উত্তর এখনও সেট করা হয়নি।",
    aiNoContext: "AI উত্তরের জন্য অন্তত একটি উৎসের ফল দরকার।",
    aiError: "AI উত্তর লোড হয়নি। অন্য উৎস চলেছে।",
    image: "ছবি",
    locations: "স্থানের রেফারেন্স",
    locationsFailed: "স্থানের রেফারেন্স লোড হয়নি।",
    map: "মানচিত্র",
    definitions: "সংজ্ঞা",
    readArticle: "নিবন্ধ পড়ুন",
    aboutResults: "প্রায় {n}টি ফল",
    resultOne: "{n}টি ফল",
    resultMany: "{n}টি ফল",
    footerSearch: "খোঁজ",
    footerAbout: "পরিচিতি",
    footerPrivacy: "গোপনীয়তা",
    footerHow: "কীভাবে খুঁজবেন",
    language: "ভাষা",
    model: "মডেল",
    searchModels: "মডেল খুঁজুন",
    homeTitle: "Zip1-এর Folio — ওয়েব, উইকিপিডিয়া ও Grokipedia খুঁজুন",
    searchedAs: "উইকিপিডিয়ায় এইভাবে খোঁজা হয়েছে",
    webSearchedAs: "ওয়েবে এইভাবে খোঁজা হয়েছে",
    queryTranslateFailed: "আপনার শব্দগুলো অনুবাদ করা যায়নি, তাই যেমন লিখেছেন তেমনই খোঁজা হয়েছে।",
    listTranslateFailed: "Grokipedia-র ফলাফল অনুবাদ করা যায়নি, তাই ইংরেজিতে দেখানো হচ্ছে।",
    translatePartial: "এই লেখার কিছু অংশ অনুবাদ করা যায়নি, সেগুলো মূল ভাষায় দেখানো হচ্ছে।",
    grokSearchedAs: "Grokipedia (শুধু ইংরেজি) এইভাবে খোঁজা হয়েছে",
    shareText: "Folio-তে “{q}”-এর খোঁজের ফল",
    aiModels: "AI মডেল",
    noModels: "কোনো মডেল নেই",
    selected: "বাছাই করা",
    sourceN: "উৎস {n}: {title}",
    pages: "{label}-এর পাতা",
    noteNotSetUp: "সেট করা নেই",
    notePaidPlan: "পেইড প্ল্যান দরকার",
    listen: "শুনুন",
    listenAnswer: "উত্তর শুনুন",
    pause: "বিরতি",
    resume: "আবার চালান",
    stop: "পড়া বন্ধ",
    closePlayer: "প্লেয়ার বন্ধ",
    close: "বন্ধ",
    previousResult: "আগের ফল",
    nextResult: "পরের ফল",
    openPage: "পাতা খুলুন",
    fullImage: "পূর্ণ ছবি দেখুন",
    loadingPreview: "পূর্ণ প্রিভিউ লোড হচ্ছে…",
    errorTitle: "কিছু একটা ভুল হয়েছে",
    errorRetry: "আবার চেষ্টা করুন",
    errorHome: "হোম পেজে যান",
    errorTranslateHint: "পেজটি আপডেট হওয়ার সময় ব্রাউজারের অনুবাদ টুল হয়তো এটি বদলে দিয়েছে। আবার চেষ্টা করুন, অথবা এই সাইটের জন্য পেজ অনুবাদ বন্ধ করে ভাষার মেনু ব্যবহার করুন।",
    readingPage: "পেজটি পড়া হচ্ছে…",
    pageUnavailable: "এই সাইটটি এখানে পড়া যায়নি (সাইটটি বাইরের অ্যাক্সেস আটকাতে পারে)। সার্চের সংক্ষিপ্ত অংশ দেখানো হচ্ছে; পুরোটা পড়তে পেজটি খুলুন।",
    showContents: "সূচি দেখান",
    hideContents: "সূচি লুকান",
    translating: "অনুবাদ হচ্ছে…",
    translateFailed: "অনুবাদ লোড হয়নি। আসল লেখা এখনও দেখা যাচ্ছে।",
    noVoice: "এই ব্রাউজারে এই ভাষার কোনো কণ্ঠ ইনস্টল করা নেই, তাই পড়ার জন্য অন্য কণ্ঠ ব্যবহার হতে পারে।",
    controls: "পড়ার নিয়ন্ত্রণ",
    speed: "পড়ার গতি",
    voices: "কণ্ঠ",
    sharePage: "এই পাতা শেয়ার করুন",
    contents: "সূচি",
    backToSearch: "খোঁজে ফিরে যান",
    englishOnly: "এই পাতার পুরো লেখা শুধু ইংরেজিতে আছে।",
  },
  "hi-IN": {
    search: "खोजें",
    clearSearch: "खोज मिटाएँ",
    trending: "अभी चर्चा में",
    recent: "हाल की",
    clear: "मिटाएँ",
    h1: "वेब, विकिपीडिया और Grokipedia खोजें",
    blurb: "Zip1 के Folio से वेब खोजें। एक सरल खोज में वेब परिणाम और वैकल्पिक विकिपीडिया तथा Grokipedia स्रोत देखें।",
    howTitle: "Folio कैसे काम करता है",
    how1: "खोज पट्टी में प्रश्न लिखें और खोज बटन दबाएँ। उसी पट्टी का मॉडल मेनू चुनता है कि छोटा AI उत्तर कौन सा मॉडल लिखे। हर खोज में वह उत्तर आता है, और जिन परिणामों का उसने उपयोग किया उनकी संख्या लिंक में होती है। उत्तर गलत हो सकता है या कुछ छोड़ सकता है, इसलिए नीचे की सूचियाँ जाँच के लिए हैं।",
    how2: "वेब परिणाम शामिल रहते हैं। विकिपीडिया और Grokipedia शुरू में चालू रहते हैं, और दोनों बंद किए जा सकते हैं। चित्र शुरू में बंद रहते हैं। चालू करने पर Bing के सार्वजनिक चित्र जुड़ते हैं। यदि वेब, विकिपीडिया, Grokipedia और चित्र सब बंद हों, तो खोज बटन तब तक निष्क्रिय रहता है जब तक एक स्रोत फिर चालू न हो। खोज के बाद ये स्विच खोज बॉक्स के साथ रहते हैं। इस पृष्ठ पर वे तब तक छिपे रहते हैं जब तक हर स्रोत बंद न हो।",
    how3before: "किसी परिणाम को चुनने पर इसी विंडो में पूर्वावलोकन खुलता है। पृष्ठ खोलें Folio छोड़कर उसी विंडो में उस पते पर जाता है।",
    howTo: "कैसे खोजें",
    how3mid: "मॉडल मेनू, पृष्ठ और पूर्वावलोकन समझाता है।",
    about: "Folio के बारे में",
    how3after: "बताता है कि यह साइट क्या है और क्या नहीं।",
    sourcesOff: "खोजने के लिए वेब, विकिपीडिया, Grokipedia या चित्र चालू करें।",
    web: "वेब",
    wiki: "विकिपीडिया",
    grok: "Grokipedia",
    images: "चित्र",
    on: "चालू",
    off: "बंद",
    optional: "वैकल्पिक",
    nothing: "कुछ नहीं मिला। कम शब्द आज़माएँ, या दूसरा स्रोत चालू करें।",
    searchFor: "खोज",
    noResponse: "{source} ने उत्तर नहीं दिया। बाकी स्रोत चलते रहे।",
    nothingPage: "इस पृष्ठ पर कुछ नहीं।",
    noMatches: "{source} में कोई मिलान नहीं।",
    openNew: "{title} नई टैब में खोलें",
    webNote: "वेब सूची Bing की सार्वजनिक परिणाम फ़ीड से है।",
    imagesNote: "चित्र Bing के सार्वजनिक चित्र परिणामों से हैं, SafeSearch मध्यम पर है।",
    shareResults: "ये परिणाम साझा करें",
    previous: "पिछला",
    next: "अगला",
    page: "{label} पृष्ठ {n}",
    deepDive: "{topic} की गहरी खोज",
    aiAnswer: "AI उत्तर",
    aiBadge: "AI द्वारा लिखा · गलत हो सकता है",
    asking: "शीर्ष परिणामों से छोटा उत्तर {model} से माँगा जा रहा है…",
    writing: "शीर्ष परिणामों से छोटा उत्तर लिखा जा रहा है…",
    tryAgain: "फिर कोशिश करें",
    failedSo: "{failed} ने उत्तर नहीं दिया, इसलिए {provider} ने दिया।",
    writtenBy: "{provider} ({model}) ने इस पृष्ठ के परिणामों से लिखा। यह गलत हो सकता है या कुछ छोड़ सकता है, इसलिए स्रोत जाँचें।",
    checkSources: "स्रोत जाँचें",
    aiUnconfigured: "AI उत्तर अभी सेट नहीं हैं।",
    aiNoContext: "AI उत्तर के लिए कम से कम एक स्रोत के परिणाम चाहिए।",
    aiError: "AI उत्तर लोड नहीं हुआ। बाकी स्रोत चलते रहे।",
    image: "चित्र",
    locations: "स्थान संदर्भ",
    locationsFailed: "स्थान संदर्भ लोड नहीं हुए।",
    map: "नक्शा",
    definitions: "परिभाषाएँ",
    readArticle: "लेख पढ़ें",
    aboutResults: "लगभग {n} परिणाम",
    resultOne: "{n} परिणाम",
    resultMany: "{n} परिणाम",
    footerSearch: "खोज",
    footerAbout: "परिचय",
    footerPrivacy: "गोपनीयता",
    footerHow: "कैसे खोजें",
    language: "भाषा",
    model: "मॉडल",
    searchModels: "मॉडल खोजें",
    homeTitle: "Zip1 का Folio — वेब, विकिपीडिया और Grokipedia खोजें",
    searchedAs: "विकिपीडिया में इस रूप में खोजा गया",
    webSearchedAs: "वेब पर इस रूप में खोजा गया",
    queryTranslateFailed: "आपके शब्दों का अनुवाद नहीं हो सका, इसलिए उन्हें जैसा लिखा था वैसा ही खोजा गया।",
    listTranslateFailed: "Grokipedia के परिणामों का अनुवाद नहीं हो सका, इसलिए वे अंग्रेज़ी में दिख रहे हैं।",
    translatePartial: "इस पाठ के कुछ हिस्सों का अनुवाद नहीं हो सका और वे मूल भाषा में दिख रहे हैं।",
    grokSearchedAs: "Grokipedia (केवल अंग्रेज़ी) में इस रूप में खोजा गया",
    shareText: "Folio पर “{q}” के खोज परिणाम",
    aiModels: "AI मॉडल",
    noModels: "कोई मॉडल नहीं",
    selected: "चुना गया",
    sourceN: "स्रोत {n}: {title}",
    pages: "{label} के पृष्ठ",
    noteNotSetUp: "सेट नहीं है",
    notePaidPlan: "सशुल्क योजना चाहिए",
    listen: "सुनें",
    listenAnswer: "उत्तर सुनें",
    pause: "रोकें",
    resume: "फिर चलाएँ",
    stop: "पढ़ना बंद करें",
    closePlayer: "प्लेयर बंद करें",
    close: "बंद करें",
    previousResult: "पिछला परिणाम",
    nextResult: "अगला परिणाम",
    openPage: "पृष्ठ खोलें",
    fullImage: "पूरा चित्र देखें",
    loadingPreview: "पूरा पूर्वावलोकन लोड हो रहा है…",
    errorTitle: "कुछ गलत हो गया",
    errorRetry: "फिर से कोशिश करें",
    errorHome: "होम पेज पर जाएँ",
    errorTranslateHint: "पेज अपडेट होते समय शायद ब्राउज़र के अनुवाद टूल ने इसे बदल दिया। फिर से कोशिश करें, या इस साइट के लिए पेज अनुवाद बंद करके भाषा मेनू का उपयोग करें।",
    readingPage: "पेज पढ़ा जा रहा है…",
    pageUnavailable: "यह साइट यहाँ नहीं पढ़ी जा सकी (हो सकता है वह बाहरी पहुँच रोकती हो)। खोज का अंश दिखाया जा रहा है; पूरा पढ़ने के लिए पेज खोलें।",
    showContents: "विषय सूची दिखाएँ",
    hideContents: "विषय सूची छिपाएँ",
    translating: "अनुवाद हो रहा है…",
    translateFailed: "अनुवाद लोड नहीं हुआ। मूल पाठ अभी भी दिख रहा है।",
    noVoice: "इस ब्राउज़र में इस भाषा की कोई आवाज़ इंस्टॉल नहीं है, इसलिए पढ़ने के लिए कोई और आवाज़ इस्तेमाल हो सकती है।",
    controls: "पढ़ने के नियंत्रण",
    speed: "पढ़ने की गति",
    voices: "आवाज़ें",
    sharePage: "यह पृष्ठ साझा करें",
    contents: "विषय सूची",
    backToSearch: "खोज पर लौटें",
    englishOnly: "इस पृष्ठ का पूरा पाठ केवल अंग्रेज़ी में उपलब्ध है।",
  },
  "ar-SA": {
    search: "بحث",
    clearSearch: "مسح البحث",
    trending: "الأكثر رواجًا الآن",
    recent: "عمليات البحث الأخيرة",
    clear: "مسح",
    h1: "ابحث في الويب وويكيبيديا وGrokipedia",
    blurb: "ابحث في الويب باستخدام Folio من Zip1. استكشف نتائج الويب ومصادر اختيارية من ويكيبيديا وGrokipedia من واجهة بحث واحدة بسيطة.",
    howTitle: "كيف يعمل Folio",
    how1: "اكتب استعلامًا في شريط البحث واضغط زر البحث. تختار قائمة النماذج في ذلك الشريط النموذج الذي يكتب إجابة الذكاء الاصطناعي القصيرة. تتضمن كل عملية بحث تلك الإجابة، مع روابط مرقّمة إلى النتائج التي استخدمتها. قد تكون الإجابة خاطئة أو ناقصة، لذا فالقوائم أسفلها موجودة للتحقق.",
    how2: "نتائج الويب مضمّنة دائمًا. تبدأ ويكيبيديا وGrokipedia مفعّلتين، ويمكنك إيقاف أي منهما. تبدأ الصور متوقفة، وتشغيلها يضيف صورًا من نتائج الصور العامة في Bing. إذا أُوقفت الويب وويكيبيديا وGrokipedia والصور جميعًا، يبقى زر البحث معطّلًا حتى تفعّل أحدها من جديد. بعد البحث، تظهر هذه المفاتيح بجانب مربع البحث. وفي هذه الصفحة تبقى مخفية حتى تُوقف كل المصادر.",
    how3before: "اختر نتيجة لفتح معاينة في هذه النافذة. يغادر زر «فتح الصفحة» موقع Folio وينتقل إلى ذلك العنوان في النافذة نفسها.",
    howTo: "كيفية البحث",
    how3mid: "تشرح قائمة النماذج والصفحات والمعاينات.",
    about: "حول Folio",
    how3after: "تشرح ما هو هذا الموقع وما ليس هو.",
    sourcesOff: "فعّل الويب أو ويكيبيديا أو Grokipedia أو الصور للبحث.",
    web: "الويب",
    wiki: "ويكيبيديا",
    grok: "Grokipedia",
    images: "الصور",
    on: "مفعّل",
    off: "متوقف",
    optional: "اختياري",
    nothing: "لا توجد نتائج مطابقة. جرّب كلمات أقل، أو فعّل مصدرًا آخر.",
    searchFor: "البحث عن",
    noResponse: "لم يستجب {source}. اكتمل البحث في المصادر الأخرى.",
    nothingPage: "لا شيء في هذه الصفحة.",
    noMatches: "لا توجد نتائج مطابقة في {source}.",
    openNew: "فتح {title} في علامة تبويب جديدة",
    webNote: "قوائم الويب من موجز نتائج Bing العامة.",
    imagesNote: "الصور من نتائج الصور العامة في Bing، مع ضبط البحث الآمن على متوسط.",
    shareResults: "مشاركة هذه النتائج",
    previous: "السابق",
    next: "التالي",
    page: "{label} الصفحة {n}",
    deepDive: "تعمّق في {topic}",
    aiAnswer: "إجابة الذكاء الاصطناعي",
    aiBadge: "من إنشاء الذكاء الاصطناعي · قد تكون خاطئة",
    asking: "جارٍ طلب إجابة قصيرة من {model} استنادًا إلى أفضل النتائج…",
    writing: "جارٍ كتابة إجابة قصيرة استنادًا إلى أفضل النتائج…",
    tryAgain: "إعادة المحاولة",
    failedSo: "لم يُجب {failed}، لذا أجاب {provider}.",
    writtenBy: "كتبها {provider} ({model}) استنادًا إلى نتائج هذه الصفحة. قد تكون خاطئة أو ناقصة، لذا تحقّق من المصادر.",
    checkSources: "تحقّق من المصادر",
    aiUnconfigured: "لم يتم إعداد إجابات الذكاء الاصطناعي بعد.",
    aiNoContext: "تحتاج إجابات الذكاء الاصطناعي إلى نتائج من مصدر واحد على الأقل.",
    aiError: "لم يتم تحميل إجابة الذكاء الاصطناعي. اكتمل البحث في المصادر الأخرى.",
    image: "صورة",
    locations: "مراجع الأماكن",
    locationsFailed: "لم يتم تحميل مراجع الأماكن.",
    map: "خريطة",
    definitions: "التعريفات",
    readArticle: "اقرأ المقال",
    aboutResults: "حوالي {n} نتيجة",
    resultOne: "نتيجة واحدة ({n})",
    resultMany: "{n} نتيجة",
    footerSearch: "بحث",
    footerAbout: "حول",
    footerPrivacy: "الخصوصية",
    footerHow: "كيفية البحث",
    language: "اللغة",
    model: "النموذج",
    searchModels: "البحث في النماذج",
    homeTitle: "Folio من Zip1 — ابحث في الويب وويكيبيديا وGrokipedia",
    searchedAs: "تم البحث في ويكيبيديا بعبارة",
    webSearchedAs: "تم البحث في الويب بعبارة",
    queryTranslateFailed: "تعذّرت ترجمة كلماتك، لذا تم البحث بها كما كُتبت.",
    listTranslateFailed: "تعذّرت ترجمة نتائج Grokipedia، لذا تظهر بالإنجليزية.",
    translatePartial: "تعذّرت ترجمة جزء من هذا النص، ويظهر بلغته الأصلية.",
    grokSearchedAs: "تم البحث في Grokipedia (بالإنجليزية فقط) بعبارة",
    shareText: "نتائج البحث عن «{q}» على Folio",
    aiModels: "نماذج الذكاء الاصطناعي",
    noModels: "لا توجد نماذج",
    selected: "محدد",
    sourceN: "المصدر {n}: {title}",
    pages: "صفحات {label}",
    noteNotSetUp: "غير مُعدّ",
    notePaidPlan: "يتطلب خطة مدفوعة",
    listen: "استمع",
    listenAnswer: "استمع إلى الإجابة",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    stop: "إيقاف القراءة",
    closePlayer: "إغلاق المشغّل",
    close: "إغلاق",
    previousResult: "النتيجة السابقة",
    nextResult: "النتيجة التالية",
    openPage: "فتح الصفحة",
    fullImage: "عرض الصورة بالحجم الكامل",
    loadingPreview: "جارٍ تحميل المعاينة الكاملة…",
    errorTitle: "حدث خطأ ما",
    errorRetry: "إعادة المحاولة",
    errorHome: "الانتقال إلى الصفحة الرئيسية",
    errorTranslateHint: "ربما غيّرت أداة الترجمة في المتصفح هذه الصفحة أثناء تحديثها. أعد المحاولة، أو أوقف ترجمة الصفحة لهذا الموقع واستخدم قائمة اللغة بدلًا منها.",
    readingPage: "جارٍ قراءة الصفحة…",
    pageUnavailable: "تعذّرت قراءة هذا الموقع هنا (قد يمنع الوصول الخارجي). يظهر مقتطف البحث؛ افتح الصفحة لقراءتها كاملة.",
    showContents: "إظهار المحتويات",
    hideContents: "إخفاء المحتويات",
    translating: "جارٍ الترجمة…",
    translateFailed: "لم يتم تحميل الترجمة. لا يزال النص الأصلي معروضًا.",
    noVoice: "لا يحتوي هذا المتصفح على صوت مثبّت لهذه اللغة، لذا قد تستخدم القراءة صوتًا آخر.",
    controls: "عناصر التحكم في القراءة",
    speed: "سرعة القراءة",
    voices: "الأصوات",
    sharePage: "مشاركة هذه الصفحة",
    contents: "المحتويات",
    backToSearch: "العودة إلى البحث",
    englishOnly: "النص الكامل لهذه الصفحة متاح باللغة الإنجليزية فقط.",
  },
  "es-ES": {
    search: "Buscar",
    clearSearch: "Borrar búsqueda",
    trending: "Tendencias",
    recent: "Recientes",
    clear: "Borrar",
    h1: "Busca en la web, Wikipedia y Grokipedia",
    blurb: "Busca en la web con Folio de Zip1. Explora resultados web y, si quieres, fuentes de Wikipedia y Grokipedia desde una sola interfaz de búsqueda sencilla.",
    howTitle: "Cómo funciona Folio",
    how1: "Escribe una consulta en la barra de búsqueda y pulsa el botón de buscar. El menú de modelos de esa barra elige qué modelo escribe la breve respuesta de IA. Cada búsqueda incluye esa respuesta, con enlaces numerados a los resultados que usó. La respuesta puede contener errores u omitir cosas, así que las listas de debajo sirven para comprobarla.",
    how2: "Los resultados web siempre se incluyen. Wikipedia y Grokipedia empiezan activadas y puedes desactivar cualquiera de las dos. Imágenes empieza desactivada; al activarla se añaden fotos de los resultados públicos de imágenes de Bing. Si Web, Wikipedia, Grokipedia e Imágenes están todas desactivadas, el botón de buscar sigue deshabilitado hasta que vuelvas a activar una. Después de buscar, esos interruptores aparecen junto al cuadro de búsqueda. En esta página permanecen ocultos hasta que todas las fuentes están desactivadas.",
    how3before: "Selecciona un resultado para abrir una vista previa en esta ventana. Abrir página sale de Folio y va a esa dirección en la misma ventana.",
    howTo: "Cómo buscar",
    how3mid: "explica el menú de modelos, las páginas y las vistas previas.",
    about: "Acerca de Folio",
    how3after: "explica qué es este sitio y qué no es.",
    sourcesOff: "Activa Web, Wikipedia, Grokipedia o Imágenes para buscar.",
    web: "Web",
    wiki: "Wikipedia",
    grok: "Grokipedia",
    images: "Imágenes",
    on: "Activo",
    off: "Inactivo",
    optional: "opcional",
    nothing: "No hay coincidencias. Prueba con menos palabras o activa otra fuente.",
    searchFor: "Búsqueda de",
    noResponse: "{source} no respondió. Las demás fuentes sí se consultaron.",
    nothingPage: "No hay nada en esta página.",
    noMatches: "No hay coincidencias en {source}.",
    openNew: "Abrir {title} en una pestaña nueva",
    webNote: "Resultados web del feed público de resultados de Bing.",
    imagesNote: "Imágenes de los resultados públicos de imágenes de Bing, con SafeSearch en moderado.",
    shareResults: "Compartir estos resultados",
    previous: "Anterior",
    next: "Siguiente",
    page: "{label}: página {n}",
    deepDive: "Profundiza en {topic}",
    aiAnswer: "Respuesta de IA",
    aiBadge: "Generada por IA · puede contener errores",
    asking: "Pidiendo a {model} una respuesta breve a partir de los mejores resultados…",
    writing: "Escribiendo una respuesta breve a partir de los mejores resultados…",
    tryAgain: "Reintentar",
    failedSo: "{failed} no respondió, así que respondió {provider}.",
    writtenBy: "Escrita por {provider} ({model}) a partir de los resultados de esta página. Puede contener errores u omitir cosas, así que comprueba las fuentes.",
    checkSources: "comprueba las fuentes",
    aiUnconfigured: "Las respuestas de IA aún no están configuradas.",
    aiNoContext: "Las respuestas de IA necesitan resultados de al menos una fuente.",
    aiError: "La respuesta de IA no se cargó. Las demás fuentes sí se consultaron.",
    image: "Imagen",
    locations: "Referencias de lugares",
    locationsFailed: "Las referencias de lugares no se cargaron.",
    map: "Mapa",
    definitions: "Definiciones",
    readArticle: "Leer el artículo",
    aboutResults: "Unos {n} resultados",
    resultOne: "{n} resultado",
    resultMany: "{n} resultados",
    footerSearch: "Buscar",
    footerAbout: "Acerca de",
    footerPrivacy: "Privacidad",
    footerHow: "Cómo buscar",
    language: "Idioma",
    model: "Modelo",
    searchModels: "Buscar modelos",
    homeTitle: "Folio de Zip1 — Busca en la web, Wikipedia y Grokipedia",
    searchedAs: "Wikipedia se buscó como",
    webSearchedAs: "La web se buscó como",
    queryTranslateFailed: "No se pudieron traducir tus palabras, así que se buscaron tal como las escribiste.",
    listTranslateFailed: "No se pudieron traducir los resultados de Grokipedia; se muestran en inglés.",
    translatePartial: "Parte de este texto no se pudo traducir y se muestra en el idioma original.",
    grokSearchedAs: "Grokipedia (solo en inglés) se buscó como",
    shareText: "Resultados de búsqueda de “{q}” en Folio",
    aiModels: "Modelos de IA",
    noModels: "No hay modelos",
    selected: "Seleccionado",
    sourceN: "Fuente {n}: {title}",
    pages: "Páginas de {label}",
    noteNotSetUp: "sin configurar",
    notePaidPlan: "requiere un plan de pago",
    listen: "Escuchar",
    listenAnswer: "Escuchar la respuesta",
    pause: "Pausar",
    resume: "Reanudar",
    stop: "Detener lectura",
    closePlayer: "Cerrar reproductor",
    close: "Cerrar",
    previousResult: "Resultado anterior",
    nextResult: "Resultado siguiente",
    openPage: "Abrir página",
    fullImage: "Ver imagen a tamaño completo",
    loadingPreview: "Cargando la vista previa completa…",
    errorTitle: "Algo salió mal",
    errorRetry: "Reintentar",
    errorHome: "Ir a la página de inicio",
    errorTranslateHint: "Es posible que una herramienta de traducción del navegador haya modificado esta página mientras se actualizaba. Vuelve a intentarlo o desactiva la traducción de páginas para este sitio y usa el menú de idioma.",
    readingPage: "Leyendo la página…",
    pageUnavailable: "No se pudo leer este sitio aquí (puede bloquear el acceso externo). Se muestra el fragmento de la búsqueda; abre la página para leerla completa.",
    showContents: "Mostrar contenido",
    hideContents: "Ocultar contenido",
    translating: "Traduciendo…",
    translateFailed: "La traducción no se cargó. Se sigue mostrando el texto original.",
    noVoice: "Este navegador no tiene ninguna voz instalada para este idioma, así que la lectura puede usar otra voz.",
    controls: "Controles de lectura",
    speed: "Velocidad de lectura",
    voices: "Voces",
    sharePage: "Compartir esta página",
    contents: "Contenido",
    backToSearch: "Volver a la búsqueda",
    englishOnly: "El texto completo de esta página solo está disponible en inglés.",
  },
  "fr-FR": {
    search: "Rechercher",
    clearSearch: "Effacer la recherche",
    trending: "Tendances",
    recent: "Récentes",
    clear: "Effacer",
    h1: "Recherchez sur le Web, Wikipédia et Grokipedia",
    blurb: "Recherchez sur le Web avec Folio par Zip1. Parcourez les résultats Web et, en option, Wikipédia et Grokipedia depuis une seule interface de recherche simple.",
    howTitle: "Comment fonctionne Folio",
    how1: "Saisissez une requête dans la barre de recherche et appuyez sur le bouton de recherche. Le menu des modèles de cette barre choisit le modèle qui rédige la courte réponse d’IA. Chaque recherche inclut cette réponse, avec des liens numérotés vers les résultats utilisés. La réponse peut être fausse ou incomplète : les listes en dessous servent à vérifier.",
    how2: "Les résultats Web sont toujours inclus. Wikipédia et Grokipedia sont activés au départ, et vous pouvez désactiver l’un ou l’autre. Images est désactivé au départ ; l’activer ajoute des photos issues des résultats d’images publics de Bing. Si Web, Wikipédia, Grokipedia et Images sont tous désactivés, le bouton de recherche reste inactif jusqu’à ce que l’un d’eux soit réactivé. Après une recherche, ces interrupteurs se trouvent à côté du champ de recherche. Sur cette page, ils restent masqués tant que toutes les sources ne sont pas désactivées.",
    how3before: "Sélectionnez un résultat pour ouvrir un aperçu dans cette fenêtre. Ouvrir la page quitte Folio et va à cette adresse dans la même fenêtre.",
    howTo: "Comment rechercher",
    how3mid: "explique le menu des modèles, les pages et les aperçus.",
    about: "À propos de Folio",
    how3after: "explique ce qu’est ce site et ce qu’il n’est pas.",
    sourcesOff: "Activez Web, Wikipédia, Grokipedia ou Images pour rechercher.",
    web: "Web",
    wiki: "Wikipédia",
    grok: "Grokipedia",
    images: "Images",
    on: "Activé",
    off: "Désactivé",
    optional: "facultatif",
    nothing: "Aucun résultat. Essayez avec moins de mots ou activez une autre source.",
    searchFor: "Recherche de",
    noResponse: "{source} n’a pas répondu. Les autres sources ont quand même été interrogées.",
    nothingPage: "Rien sur cette page.",
    noMatches: "Aucun résultat dans {source}.",
    openNew: "Ouvrir {title} dans un nouvel onglet",
    webNote: "Résultats Web issus du flux de résultats publics de Bing.",
    imagesNote: "Images issues des résultats d’images publics de Bing, avec SafeSearch réglé sur modéré.",
    shareResults: "Partager ces résultats",
    previous: "Précédent",
    next: "Suivant",
    page: "{label}, page {n}",
    deepDive: "Approfondir : {topic}",
    aiAnswer: "Réponse de l’IA",
    aiBadge: "Générée par IA · peut être erronée",
    asking: "Demande à {model} d’une courte réponse à partir des meilleurs résultats…",
    writing: "Rédaction d’une courte réponse à partir des meilleurs résultats…",
    tryAgain: "Réessayer",
    failedSo: "{failed} n’a pas répondu, donc {provider} a pris le relais.",
    writtenBy: "Rédigée par {provider} ({model}) à partir des résultats de cette page. Elle peut être fausse ou incomplète : vérifiez les sources.",
    checkSources: "vérifiez les sources",
    aiUnconfigured: "Les réponses d’IA ne sont pas encore configurées.",
    aiNoContext: "Les réponses d’IA ont besoin des résultats d’au moins une source.",
    aiError: "La réponse d’IA ne s’est pas chargée. Les autres sources ont quand même été interrogées.",
    image: "Image",
    locations: "Lieux mentionnés",
    locationsFailed: "Les lieux mentionnés ne se sont pas chargés.",
    map: "Carte",
    definitions: "Définitions",
    readArticle: "Lire l’article",
    aboutResults: "Environ {n} résultats",
    resultOne: "{n} résultat",
    resultMany: "{n} résultats",
    footerSearch: "Recherche",
    footerAbout: "À propos",
    footerPrivacy: "Confidentialité",
    footerHow: "Comment rechercher",
    language: "Langue",
    model: "Modèle",
    searchModels: "Rechercher un modèle",
    homeTitle: "Folio par Zip1 — Recherche Web, Wikipédia et Grokipedia",
    searchedAs: "Wikipédia a été interrogé avec",
    webSearchedAs: "Le Web a été interrogé avec",
    queryTranslateFailed: "Vos mots n’ont pas pu être traduits ; la recherche a utilisé le texte saisi.",
    listTranslateFailed: "Les résultats de Grokipedia n’ont pas pu être traduits et sont affichés en anglais.",
    translatePartial: "Une partie de ce texte n’a pas pu être traduite et reste dans sa langue d’origine.",
    grokSearchedAs: "Grokipedia (en anglais uniquement) a été interrogé avec",
    shareText: "Résultats de recherche pour « {q} » sur Folio",
    aiModels: "Modèles d’IA",
    noModels: "Aucun modèle",
    selected: "Sélectionné",
    sourceN: "Source {n} : {title}",
    pages: "Pages {label}",
    noteNotSetUp: "non configuré",
    notePaidPlan: "nécessite un forfait payant",
    listen: "Écouter",
    listenAnswer: "Écouter la réponse",
    pause: "Mettre en pause",
    resume: "Reprendre",
    stop: "Arrêter la lecture",
    closePlayer: "Fermer le lecteur",
    close: "Fermer",
    previousResult: "Résultat précédent",
    nextResult: "Résultat suivant",
    openPage: "Ouvrir la page",
    fullImage: "Voir l’image en taille réelle",
    loadingPreview: "Chargement de l’aperçu complet…",
    errorTitle: "Un problème est survenu",
    errorRetry: "Réessayer",
    errorHome: "Aller à la page d’accueil",
    errorTranslateHint: "Un outil de traduction du navigateur a peut-être modifié cette page pendant sa mise à jour. Réessayez, ou désactivez la traduction de page pour ce site et utilisez plutôt le menu des langues.",
    readingPage: "Lecture de la page…",
    pageUnavailable: "Ce site n’a pas pu être lu ici (il bloque peut-être l’accès extérieur). L’extrait de recherche est affiché ; ouvrez la page pour tout lire.",
    showContents: "Afficher le sommaire",
    hideContents: "Masquer le sommaire",
    translating: "Traduction en cours…",
    translateFailed: "La traduction ne s’est pas chargée. Le texte original reste affiché.",
    noVoice: "Ce navigateur n’a aucune voix installée pour cette langue ; la lecture peut utiliser une autre voix.",
    controls: "Commandes de lecture",
    speed: "Vitesse de lecture",
    voices: "Voix",
    sharePage: "Partager cette page",
    contents: "Sommaire",
    backToSearch: "Retour à la recherche",
    englishOnly: "Le texte complet de cette page n’est disponible qu’en anglais.",
  },
  "zh-CN": {
    search: "搜索",
    clearSearch: "清除搜索",
    trending: "正在流行",
    recent: "最近",
    clear: "清除",
    h1: "搜索网页、维基百科和 Grokipedia",
    blurb: "用 Zip1 的 Folio 搜索网页。在一个简单的界面里查看网页结果，以及可选的维基百科和 Grokipedia。",
    howTitle: "Folio 如何工作",
    how1: "在搜索栏输入查询并按下搜索按钮。栏内的模型菜单决定由哪个模型写简短的 AI 回答。每次搜索都包含这个回答，并用数字链到它用过的结果。回答可能有错或有遗漏，所以下面的列表用来核对。",
    how2: "网页结果默认包含。维基百科和 Grokipedia 默认打开，可以关掉。图片默认关闭。打开后会加入 Bing 公开图片结果。如果网页、维基百科、Grokipedia 和图片都关闭，搜索按钮会保持禁用，直到重新打开其中一项。搜索之后，这些开关跟在搜索框旁边。在本页，它们会一直隐藏，直到所有来源都关闭。",
    how3before: "点一条结果，会在这个窗口里打开预览。打开页面会离开 Folio，并在同一窗口前往那个地址。",
    howTo: "如何搜索",
    how3mid: "说明模型菜单、翻页和预览。",
    about: "关于 Folio",
    how3after: "说明这个网站是什么，以及它不是什么。",
    sourcesOff: "请打开网页、维基百科、Grokipedia 或图片后再搜索。",
    web: "网页",
    wiki: "维基百科",
    grok: "Grokipedia",
    images: "图片",
    on: "开",
    off: "关",
    optional: "可选",
    nothing: "没有匹配。试着少用几个词，或打开另一个来源。",
    searchFor: "搜索",
    noResponse: "{source} 没有响应。其他来源仍已完成。",
    nothingPage: "这一页没有内容。",
    noMatches: "{source} 中没有匹配。",
    openNew: "在新标签页打开 {title}",
    webNote: "网页列表来自 Bing 的公开结果。",
    imagesNote: "图片来自 Bing 的公开图片结果，安全搜索设为中等。",
    shareResults: "分享这些结果",
    previous: "上一页",
    next: "下一页",
    page: "{label} 第 {n} 页",
    deepDive: "深入了解 {topic}",
    aiAnswer: "AI 回答",
    aiBadge: "AI 生成 · 可能有误",
    asking: "正在请 {model} 根据最前面的结果写一段简短回答…",
    writing: "正在根据最前面的结果写一段简短回答…",
    tryAgain: "重试",
    failedSo: "{failed} 没有回答，所以由 {provider} 来写。",
    writtenBy: "由 {provider}（{model}）根据本页结果写成。它可能有错或有遗漏，请核对来源。",
    checkSources: "核对来源",
    aiUnconfigured: "AI 回答尚未设置。",
    aiNoContext: "AI 回答至少需要一个来源的结果。",
    aiError: "AI 回答没有加载。其他来源仍已完成。",
    image: "图片",
    locations: "地点参考",
    locationsFailed: "地点参考没有加载。",
    map: "地图",
    definitions: "释义",
    readArticle: "阅读文章",
    aboutResults: "约 {n} 条结果",
    resultOne: "{n} 条结果",
    resultMany: "{n} 条结果",
    footerSearch: "搜索",
    footerAbout: "关于",
    footerPrivacy: "隐私",
    footerHow: "如何搜索",
    language: "语言",
    model: "模型",
    searchModels: "搜索模型",
    homeTitle: "Zip1 的 Folio — 搜索网页、维基百科和 Grokipedia",
    searchedAs: "维基百科按此搜索",
    webSearchedAs: "网页按此搜索",
    queryTranslateFailed: "无法翻译你输入的词语，因此按原文搜索。",
    listTranslateFailed: "无法翻译 Grokipedia 的结果，因此以英文显示。",
    translatePartial: "部分文字无法翻译，以原文显示。",
    grokSearchedAs: "Grokipedia（仅英文）按此搜索",
    shareText: "Folio 上“{q}”的搜索结果",
    aiModels: "AI 模型",
    noModels: "没有模型",
    selected: "已选择",
    sourceN: "来源 {n}：{title}",
    pages: "{label} 分页",
    noteNotSetUp: "未设置",
    notePaidPlan: "需要付费方案",
    listen: "朗读",
    listenAnswer: "朗读回答",
    pause: "暂停",
    resume: "继续",
    stop: "停止朗读",
    closePlayer: "关闭播放器",
    close: "关闭",
    previousResult: "上一条",
    nextResult: "下一条",
    openPage: "打开页面",
    fullImage: "查看大图",
    loadingPreview: "正在加载完整预览…",
    errorTitle: "出了点问题",
    errorRetry: "重试",
    errorHome: "前往首页",
    errorTranslateHint: "浏览器的翻译工具可能在页面更新时修改了此页面。请重试，或为本站关闭网页翻译，改用语言菜单。",
    readingPage: "正在读取页面…",
    pageUnavailable: "无法在此读取该网站（它可能阻止外部访问）。现显示搜索摘要；打开页面可阅读全文。",
    showContents: "显示目录",
    hideContents: "隐藏目录",
    translating: "正在翻译…",
    translateFailed: "翻译没有加载。仍显示原文。",
    noVoice: "此浏览器未安装这种语言的语音，朗读可能会使用其他语音。",
    controls: "朗读控制",
    speed: "朗读速度",
    voices: "语音",
    sharePage: "分享此页",
    contents: "目录",
    backToSearch: "返回搜索",
    englishOnly: "本页完整内容仅提供英文版。",
  },
  "ja-JP": {
    search: "検索",
    clearSearch: "検索をクリア",
    trending: "トレンド",
    recent: "最近の検索",
    clear: "クリア",
    h1: "ウェブ、ウィキペディア、Grokipedia を検索",
    blurb: "Zip1 の Folio でウェブを検索。ウェブの結果と、必要に応じてウィキペディアや Grokipedia の情報を、ひとつのシンプルな検索画面で確認できます。",
    howTitle: "Folio のしくみ",
    how1: "検索バーにキーワードを入力して検索ボタンを押します。バーのモデルメニューで、短い AI 回答を書くモデルを選べます。すべての検索にその回答が付き、使われた結果には番号付きのリンクが付きます。回答は間違っていたり抜けがあったりするので、下の一覧で確認してください。",
    how2: "ウェブの結果は常に含まれます。ウィキペディアと Grokipedia は最初からオンで、どちらもオフにできます。画像は最初はオフで、オンにすると Bing の公開画像検索の結果が加わります。ウェブ、ウィキペディア、Grokipedia、画像がすべてオフの場合、どれかをオンに戻すまで検索ボタンは無効のままです。検索後、これらのスイッチは検索ボックスの近くに表示されます。このページでは、すべてのソースがオフになるまで表示されません。",
    how3before: "結果を選ぶと、このウィンドウでプレビューが開きます。「ページを開く」は Folio を離れ、同じウィンドウでそのアドレスに移動します。",
    howTo: "検索のしかた",
    how3mid: "では、モデルメニュー、ページ、プレビューについて説明しています。",
    about: "Folio について",
    how3after: "では、このサイトが何であり、何でないかを説明しています。",
    sourcesOff: "検索するには、ウェブ、ウィキペディア、Grokipedia、画像のいずれかをオンにしてください。",
    web: "ウェブ",
    wiki: "ウィキペディア",
    grok: "Grokipedia",
    images: "画像",
    on: "オン",
    off: "オフ",
    optional: "任意",
    nothing: "一致するものがありません。単語を減らすか、別のソースをオンにしてください。",
    searchFor: "検索語",
    noResponse: "{source} から応答がありませんでした。ほかのソースは検索済みです。",
    nothingPage: "このページには何もありません。",
    noMatches: "{source} に一致するものはありません。",
    openNew: "{title} を新しいタブで開く",
    webNote: "ウェブの結果は Bing の公開検索フィードによるものです。",
    imagesNote: "画像は Bing の公開画像検索の結果で、セーフサーチは「中」です。",
    shareResults: "この結果を共有",
    previous: "前へ",
    next: "次へ",
    page: "{label} {n} ページ",
    deepDive: "{topic} をさらに詳しく",
    aiAnswer: "AI 回答",
    aiBadge: "AI 生成 · 間違いの可能性あり",
    asking: "{model} に上位の結果から短い回答を依頼しています…",
    writing: "上位の結果から短い回答を作成しています…",
    tryAgain: "再試行",
    failedSo: "{failed} が応答しなかったため、{provider} が回答しました。",
    writtenBy: "このページの結果をもとに {provider}（{model}）が作成しました。間違いや抜けがある可能性があるので、出典を確認してください。",
    checkSources: "出典を確認してください",
    aiUnconfigured: "AI 回答はまだ設定されていません。",
    aiNoContext: "AI 回答には、少なくとも 1 つのソースの結果が必要です。",
    aiError: "AI 回答を読み込めませんでした。ほかのソースは検索済みです。",
    image: "画像",
    locations: "場所の参考情報",
    locationsFailed: "場所の参考情報を読み込めませんでした。",
    map: "地図",
    definitions: "定義",
    readArticle: "記事を読む",
    aboutResults: "約 {n} 件の結果",
    resultOne: "{n} 件の結果",
    resultMany: "{n} 件の結果",
    footerSearch: "検索",
    footerAbout: "概要",
    footerPrivacy: "プライバシー",
    footerHow: "検索のしかた",
    language: "言語",
    model: "モデル",
    searchModels: "モデルを検索",
    homeTitle: "Zip1 の Folio — ウェブ、ウィキペディア、Grokipedia を検索",
    searchedAs: "ウィキペディアは次の語で検索しました",
    webSearchedAs: "ウェブは次の語で検索しました",
    queryTranslateFailed: "入力した語を翻訳できなかったため、そのまま検索しました。",
    listTranslateFailed: "Grokipedia の結果を翻訳できなかったため、英語で表示しています。",
    translatePartial: "このテキストの一部は翻訳できなかったため、元の言語で表示しています。",
    grokSearchedAs: "Grokipedia（英語のみ）は次の語で検索しました",
    shareText: "Folio での「{q}」の検索結果",
    aiModels: "AI モデル",
    noModels: "モデルがありません",
    selected: "選択中",
    sourceN: "出典 {n}: {title}",
    pages: "{label} のページ",
    noteNotSetUp: "未設定",
    notePaidPlan: "有料プランが必要",
    listen: "聞く",
    listenAnswer: "回答を聞く",
    pause: "一時停止",
    resume: "再開",
    stop: "読み上げを停止",
    closePlayer: "プレーヤーを閉じる",
    close: "閉じる",
    previousResult: "前の結果",
    nextResult: "次の結果",
    openPage: "ページを開く",
    fullImage: "フルサイズの画像を見る",
    loadingPreview: "プレビュー全体を読み込んでいます…",
    errorTitle: "問題が発生しました",
    errorRetry: "再試行",
    errorHome: "ホームページへ",
    errorTranslateHint: "ページの更新中に、ブラウザの翻訳機能がこのページを書き換えた可能性があります。もう一度お試しいただくか、このサイトではページ翻訳をオフにして言語メニューをご利用ください。",
    readingPage: "ページを読み込んでいます…",
    pageUnavailable: "このサイトはここでは読み込めませんでした（外部からのアクセスを制限している可能性があります）。検索結果の抜粋を表示しています。全文はページを開いてお読みください。",
    showContents: "目次を表示",
    hideContents: "目次を隠す",
    translating: "翻訳しています…",
    translateFailed: "翻訳を読み込めませんでした。元のテキストを表示しています。",
    noVoice: "このブラウザにはこの言語の音声がインストールされていないため、別の音声で読み上げられる場合があります。",
    controls: "読み上げの操作",
    speed: "読み上げ速度",
    voices: "音声",
    sharePage: "このページを共有",
    contents: "目次",
    backToSearch: "検索に戻る",
    englishOnly: "このページの全文は英語でのみ提供しています。",
  },
  "pt-BR": {
    search: "Pesquisar",
    clearSearch: "Limpar pesquisa",
    trending: "Em alta",
    recent: "Recentes",
    clear: "Limpar",
    h1: "Pesquise na web, na Wikipédia e na Grokipedia",
    blurb: "Pesquise na web com o Folio da Zip1. Explore resultados da web e, se quiser, fontes da Wikipédia e da Grokipedia em uma única interface de pesquisa simples.",
    howTitle: "Como o Folio funciona",
    how1: "Digite uma consulta na barra de pesquisa e toque no botão de pesquisar. O menu de modelos nessa barra escolhe qual modelo escreve a resposta curta de IA. Toda pesquisa inclui essa resposta, com links numerados para os resultados usados. A resposta pode estar errada ou deixar coisas de fora, por isso as listas abaixo dela servem para conferir.",
    how2: "Os resultados da web estão sempre incluídos. Wikipédia e Grokipedia começam ativadas, e você pode desativar qualquer uma delas. Imagens começa desativada; ao ativá-la, entram fotos dos resultados públicos de imagens do Bing. Se Web, Wikipédia, Grokipedia e Imagens estiverem todas desativadas, o botão de pesquisar fica desabilitado até que uma delas seja ativada de novo. Depois de uma pesquisa, esses botões ficam junto à caixa de pesquisa. Nesta página, eles ficam ocultos até que todas as fontes estejam desativadas.",
    how3before: "Selecione um resultado para abrir uma prévia nesta janela. Abrir página sai do Folio e vai para esse endereço na mesma janela.",
    howTo: "Como pesquisar",
    how3mid: "explica o menu de modelos, as páginas e as prévias.",
    about: "Sobre o Folio",
    how3after: "explica o que este site é e o que ele não é.",
    sourcesOff: "Ative Web, Wikipédia, Grokipedia ou Imagens para pesquisar.",
    web: "Web",
    wiki: "Wikipédia",
    grok: "Grokipedia",
    images: "Imagens",
    on: "Ativado",
    off: "Desativado",
    optional: "opcional",
    nothing: "Nada encontrado. Tente menos palavras ou ative outra fonte.",
    searchFor: "Pesquisa por",
    noResponse: "{source} não respondeu. As outras fontes foram consultadas.",
    nothingPage: "Nada nesta página.",
    noMatches: "Nenhum resultado em {source}.",
    openNew: "Abrir {title} em uma nova aba",
    webNote: "Resultados da web do feed público de resultados do Bing.",
    imagesNote: "Imagens dos resultados públicos de imagens do Bing, com SafeSearch no modo moderado.",
    shareResults: "Compartilhar estes resultados",
    previous: "Anterior",
    next: "Próxima",
    page: "{label}: página {n}",
    deepDive: "Aprofunde-se em {topic}",
    aiAnswer: "Resposta de IA",
    aiBadge: "Gerada por IA · pode conter erros",
    asking: "Pedindo a {model} uma resposta curta com base nos principais resultados…",
    writing: "Escrevendo uma resposta curta com base nos principais resultados…",
    tryAgain: "Tentar de novo",
    failedSo: "{failed} não respondeu, então {provider} respondeu.",
    writtenBy: "Escrita por {provider} ({model}) com base nos resultados desta página. Pode estar errada ou deixar coisas de fora, então confira as fontes.",
    checkSources: "confira as fontes",
    aiUnconfigured: "As respostas de IA ainda não estão configuradas.",
    aiNoContext: "As respostas de IA precisam de resultados de pelo menos uma fonte.",
    aiError: "A resposta de IA não carregou. As outras fontes foram consultadas.",
    image: "Imagem",
    locations: "Referências de lugares",
    locationsFailed: "As referências de lugares não carregaram.",
    map: "Mapa",
    definitions: "Definições",
    readArticle: "Ler o artigo",
    aboutResults: "Cerca de {n} resultados",
    resultOne: "{n} resultado",
    resultMany: "{n} resultados",
    footerSearch: "Pesquisar",
    footerAbout: "Sobre",
    footerPrivacy: "Privacidade",
    footerHow: "Como pesquisar",
    language: "Idioma",
    model: "Modelo",
    searchModels: "Pesquisar modelos",
    homeTitle: "Folio da Zip1 — Pesquise na web, na Wikipédia e na Grokipedia",
    searchedAs: "A Wikipédia foi pesquisada como",
    webSearchedAs: "A web foi pesquisada como",
    queryTranslateFailed: "Não foi possível traduzir suas palavras, então elas foram pesquisadas como digitadas.",
    listTranslateFailed: "Não foi possível traduzir os resultados da Grokipedia; eles aparecem em inglês.",
    translatePartial: "Parte deste texto não pôde ser traduzida e aparece no idioma original.",
    grokSearchedAs: "A Grokipedia (somente em inglês) foi pesquisada como",
    shareText: "Resultados da pesquisa por “{q}” no Folio",
    aiModels: "Modelos de IA",
    noModels: "Nenhum modelo",
    selected: "Selecionado",
    sourceN: "Fonte {n}: {title}",
    pages: "Páginas de {label}",
    noteNotSetUp: "não configurado",
    notePaidPlan: "requer um plano pago",
    listen: "Ouvir",
    listenAnswer: "Ouvir a resposta",
    pause: "Pausar",
    resume: "Continuar",
    stop: "Parar leitura",
    closePlayer: "Fechar player",
    close: "Fechar",
    previousResult: "Resultado anterior",
    nextResult: "Próximo resultado",
    openPage: "Abrir página",
    fullImage: "Ver imagem em tamanho real",
    loadingPreview: "Carregando a prévia completa…",
    errorTitle: "Algo deu errado",
    errorRetry: "Tentar novamente",
    errorHome: "Ir para a página inicial",
    errorTranslateHint: "Uma ferramenta de tradução do navegador pode ter alterado esta página enquanto ela era atualizada. Tente novamente ou desative a tradução de páginas para este site e use o menu de idiomas.",
    readingPage: "Lendo a página…",
    pageUnavailable: "Não foi possível ler este site aqui (ele pode bloquear o acesso externo). Mostrando o trecho da pesquisa; abra a página para ler tudo.",
    showContents: "Mostrar sumário",
    hideContents: "Ocultar sumário",
    translating: "Traduzindo…",
    translateFailed: "A tradução não carregou. O texto original continua sendo exibido.",
    noVoice: "Este navegador não tem nenhuma voz instalada para este idioma, então a leitura pode usar outra voz.",
    controls: "Controles de leitura",
    speed: "Velocidade da leitura",
    voices: "Vozes",
    sharePage: "Compartilhar esta página",
    contents: "Sumário",
    backToSearch: "Voltar à pesquisa",
    englishOnly: "O texto completo desta página está disponível apenas em inglês.",
  },
  "de-DE": {
    search: "Suchen",
    clearSearch: "Suche löschen",
    trending: "Gerade gefragt",
    recent: "Zuletzt gesucht",
    clear: "Löschen",
    h1: "Web, Wikipedia und Grokipedia durchsuchen",
    blurb: "Durchsuche das Web mit Folio von Zip1. Sieh dir Webergebnisse und optional Wikipedia- und Grokipedia-Quellen in einer einfachen Suchoberfläche an.",
    howTitle: "So funktioniert Folio",
    how1: "Gib eine Suchanfrage in die Suchleiste ein und drücke die Suchtaste. Das Modellmenü in dieser Leiste legt fest, welches Modell die kurze KI-Antwort schreibt. Jede Suche enthält diese Antwort, mit nummerierten Links zu den verwendeten Ergebnissen. Die Antwort kann falsch oder unvollständig sein, deshalb stehen die Listen darunter zum Nachprüfen.",
    how2: "Webergebnisse sind immer dabei. Wikipedia und Grokipedia sind anfangs eingeschaltet, und du kannst beide ausschalten. Bilder ist anfangs ausgeschaltet; wenn du es einschaltest, kommen Bilder aus den öffentlichen Bildergebnissen von Bing hinzu. Sind Web, Wikipedia, Grokipedia und Bilder alle aus, bleibt die Suchtaste deaktiviert, bis eine Quelle wieder an ist. Nach einer Suche stehen diese Schalter beim Suchfeld. Auf dieser Seite bleiben sie verborgen, bis alle Quellen aus sind.",
    how3before: "Wähle ein Ergebnis, um in diesem Fenster eine Vorschau zu öffnen. „Seite öffnen“ verlässt Folio und ruft diese Adresse im selben Fenster auf.",
    howTo: "So suchst du",
    how3mid: "erklärt das Modellmenü, die Seiten und die Vorschauen.",
    about: "Über Folio",
    how3after: "erklärt, was diese Website ist und was nicht.",
    sourcesOff: "Schalte Web, Wikipedia, Grokipedia oder Bilder ein, um zu suchen.",
    web: "Web",
    wiki: "Wikipedia",
    grok: "Grokipedia",
    images: "Bilder",
    on: "An",
    off: "Aus",
    optional: "optional",
    nothing: "Keine Treffer. Versuche es mit weniger Wörtern oder schalte eine weitere Quelle ein.",
    searchFor: "Suche nach",
    noResponse: "{source} hat nicht geantwortet. Die anderen Quellen wurden trotzdem abgefragt.",
    nothingPage: "Auf dieser Seite gibt es nichts.",
    noMatches: "Keine Treffer in {source}.",
    openNew: "{title} in neuem Tab öffnen",
    webNote: "Webeinträge aus dem öffentlichen Ergebnis-Feed von Bing.",
    imagesNote: "Bilder aus den öffentlichen Bildergebnissen von Bing, SafeSearch auf mittel.",
    shareResults: "Diese Ergebnisse teilen",
    previous: "Zurück",
    next: "Weiter",
    page: "{label}, Seite {n}",
    deepDive: "Mehr zu {topic}",
    aiAnswer: "KI-Antwort",
    aiBadge: "KI-generiert · kann falsch sein",
    asking: "{model} wird um eine kurze Antwort aus den besten Ergebnissen gebeten…",
    writing: "Eine kurze Antwort aus den besten Ergebnissen wird geschrieben…",
    tryAgain: "Erneut versuchen",
    failedSo: "{failed} hat nicht geantwortet, deshalb hat {provider} übernommen.",
    writtenBy: "Geschrieben von {provider} ({model}) aus den Ergebnissen auf dieser Seite. Sie kann falsch oder unvollständig sein, prüfe also die Quellen.",
    checkSources: "prüfe die Quellen",
    aiUnconfigured: "KI-Antworten sind noch nicht eingerichtet.",
    aiNoContext: "KI-Antworten brauchen Ergebnisse aus mindestens einer Quelle.",
    aiError: "Die KI-Antwort wurde nicht geladen. Die anderen Quellen wurden trotzdem abgefragt.",
    image: "Bild",
    locations: "Ortsangaben",
    locationsFailed: "Die Ortsangaben wurden nicht geladen.",
    map: "Karte",
    definitions: "Definitionen",
    readArticle: "Artikel lesen",
    aboutResults: "Etwa {n} Ergebnisse",
    resultOne: "{n} Ergebnis",
    resultMany: "{n} Ergebnisse",
    footerSearch: "Suche",
    footerAbout: "Über",
    footerPrivacy: "Datenschutz",
    footerHow: "So suchst du",
    language: "Sprache",
    model: "Modell",
    searchModels: "Modelle suchen",
    homeTitle: "Folio von Zip1 — Web, Wikipedia und Grokipedia durchsuchen",
    searchedAs: "Wikipedia wurde gesucht mit",
    webSearchedAs: "Das Web wurde gesucht mit",
    queryTranslateFailed: "Deine Wörter konnten nicht übersetzt werden, daher wurde mit der Eingabe gesucht.",
    listTranslateFailed: "Die Grokipedia-Ergebnisse konnten nicht übersetzt werden und werden auf Englisch angezeigt.",
    translatePartial: "Ein Teil dieses Textes konnte nicht übersetzt werden und wird in der Originalsprache angezeigt.",
    grokSearchedAs: "Grokipedia (nur Englisch) wurde gesucht mit",
    shareText: "Suchergebnisse für „{q}“ auf Folio",
    aiModels: "KI-Modelle",
    noModels: "Keine Modelle",
    selected: "Ausgewählt",
    sourceN: "Quelle {n}: {title}",
    pages: "{label}-Seiten",
    noteNotSetUp: "nicht eingerichtet",
    notePaidPlan: "braucht einen bezahlten Tarif",
    listen: "Anhören",
    listenAnswer: "Antwort anhören",
    pause: "Pausieren",
    resume: "Fortsetzen",
    stop: "Vorlesen beenden",
    closePlayer: "Player schließen",
    close: "Schließen",
    previousResult: "Vorheriges Ergebnis",
    nextResult: "Nächstes Ergebnis",
    openPage: "Seite öffnen",
    fullImage: "Bild in voller Größe ansehen",
    loadingPreview: "Vollständige Vorschau wird geladen…",
    errorTitle: "Etwas ist schiefgelaufen",
    errorRetry: "Erneut versuchen",
    errorHome: "Zur Startseite",
    errorTranslateHint: "Ein Übersetzungstool des Browsers hat diese Seite möglicherweise verändert, während sie aktualisiert wurde. Versuche es erneut oder schalte die Seitenübersetzung für diese Website aus und nutze stattdessen das Sprachmenü.",
    readingPage: "Seite wird gelesen…",
    pageUnavailable: "Diese Website konnte hier nicht gelesen werden (sie blockiert möglicherweise den Zugriff von außen). Es wird der Suchausschnitt angezeigt; öffne die Seite, um alles zu lesen.",
    showContents: "Inhalt anzeigen",
    hideContents: "Inhalt ausblenden",
    translating: "Wird übersetzt…",
    translateFailed: "Die Übersetzung wurde nicht geladen. Der Originaltext wird weiter angezeigt.",
    noVoice: "In diesem Browser ist keine Stimme für diese Sprache installiert, daher kann eine andere Stimme vorlesen.",
    controls: "Vorlese-Steuerung",
    speed: "Vorlesegeschwindigkeit",
    voices: "Stimmen",
    sharePage: "Diese Seite teilen",
    contents: "Inhalt",
    backToSearch: "Zurück zur Suche",
    englishOnly: "Der vollständige Text dieser Seite ist nur auf Englisch verfügbar.",
  },
};

export function fill(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => values[key] ?? "");
}

export function sourceLabel(copy: UiCopy, id: "web" | "wiki" | "grok" | "images"): string {
  if (id === "web") return copy.web;
  if (id === "wiki") return copy.wiki;
  if (id === "grok") return copy.grok;
  return copy.images;
}
